# Generated by Django 5.2 on 2025-04-29 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oportunidade',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_oportunidades/'),
        ),
    ]
