# Generated by Django 5.2 on 2025-04-29 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_oportunidade_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oportunidade',
            name='foto',
        ),
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emissao', models.DateTimeField(auto_now_add=True)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('horas', models.PositiveIntegerField()),
                ('descricao', models.TextField()),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='certificados/')),
                ('oportunidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificados', to='core.oportunidade')),
                ('voluntario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificados', to='core.voluntario')),
            ],
            options={
                'ordering': ['-data_emissao'],
            },
        ),
    ]
