# Generated by Django 5.2 on 2025-05-06 14:33

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_oportunidade_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oportunidade',
            options={},
        ),
        migrations.RenameField(
            model_name='oportunidade',
            old_name='criado_em',
            new_name='data_cadastro',
        ),
        migrations.RemoveField(
            model_name='oportunidade',
            name='atualizado_em',
        ),
        migrations.RemoveField(
            model_name='oportunidade',
            name='imagem',
        ),
        migrations.AlterField(
            model_name='oportunidade',
            name='data',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='oportunidade',
            name='local',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='oportunidade',
            name='quantidade_vagas',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='oportunidade',
            name='titulo',
            field=models.CharField(default='Sem título', max_length=255),
        ),
    ]
