# Generated by Django 5.2 on 2025-04-28 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_organizacao_foto_voluntario_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricao',
            name='curriculo',
            field=models.FileField(blank=True, null=True, upload_to='curriculos/'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='mensagem',
            field=models.TextField(blank=True, null=True),
        ),
    ]
